# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "zappos"
  s.version = "0.4.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pawel Szymczykowski"]
  s.date = "2013-03-07"
  s.description = "The Zappos API (called Patron) lets you hook into various Zappos functions such as product information, search, faceting and more."
  s.email = "pawel@zappos.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "autotest/discover.rb",
    "lib/zappos.rb",
    "lib/zappos/base_client.rb",
    "lib/zappos/client.rb",
    "lib/zappos/client/auto_complete.rb",
    "lib/zappos/client/brand.rb",
    "lib/zappos/client/core_value.rb",
    "lib/zappos/client/image.rb",
    "lib/zappos/client/product.rb",
    "lib/zappos/client/review.rb",
    "lib/zappos/client/search.rb",
    "lib/zappos/client/similarity.rb",
    "lib/zappos/client/statistics.rb",
    "lib/zappos/paginated_response.rb",
    "lib/zappos/request.rb",
    "lib/zappos/response.rb",
    "spec/fixtures/error_response.json",
    "spec/fixtures/message_response.json",
    "spec/fixtures/not_json.txt",
    "spec/fixtures/product_response.json",
    "spec/fixtures/product_stock_response.json",
    "spec/fixtures/search_response.json",
    "spec/response_spec.rb",
    "spec/spec_helper.rb",
    "spec/zappos/client/product_spec.rb",
    "spec/zappos/client/search_spec.rb",
    "spec/zappos/client_spec.rb",
    "spec/zappos_spec.rb",
    "zappos.gemspec"
  ]
  s.homepage = "http://github.com/makenai/zappos"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby bindings for the Zappos API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 1.2.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 1.2.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 1.2.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

